### ISSUE TITLE
bug(sponsorkit): various issues when retrieving Open Collective sponsorships

### ISSUE THREAD

**Issue by robingenz** [capawesome-team/static#1]
We use [sponsorkit](https://github.com/antfu/sponsorkit) for generating sponsors images ([example](https://github.com/capawesome-team/static/blob/main/images/sponsors/sponsors.png)).

However, due to https://github.com/antfu/sponsorkit/issues/57, we are currently unable to automatically retrieve the sponsorships from Open Collective and have to define them manually (see [here](https://github.com/capawesome-team/static/blob/main/sponsorkit.config.ts#L3:L50)).
The task is to create a PR in https://github.com/antfu/sponsorkit that closes this issue and allows us to remove our workaround.
I am placing a bounty of **$50** on this.

**Comment by isbecker** [comment]
Hi, I think I have good idea what the issue is and I'd like to make an attempt at solving it.

**Comment by robingenz** [comment]
Great, I assigned you!

**Comment by isbecker** [comment]
Hi @robingenz, I have submitted my PR to `antfu/sponsorkit`. Hopefully it will be merged before too long!

https://github.com/antfu/sponsorkit/pull/58

Once merged, I'd be happy to update this repo to remove [the hack](https://github.com/capawesome-team/static/blob/main/sponsorkit.config.ts#L3:L50) if you want.

**Comment by robingenz** [comment]
Great work! I hope so too. 

> Once merged, I'd be happy to update this repo to remove the hack if you want.

That would be awesome!

**Comment by isbecker** [comment]
PR opened: #2

- removed the hardcoded sponsors
- enabled the env options for OC in the workflow
  - removed the OC "type" env var since that is no longer necessary
- updated the `sponsorkit` dependency to 0.9.0

**Comment by robingenz** [comment]
@isbecker Thank you so much for your great work! All the requirements for paying out the bounty have now been met. Read more about how you get paid [here](https://capawesome.io/contributing/bounties/claim-a-bounty/#how-do-i-get-paid). Let me know if you have any questions.

You are very welcome to contribute to our projects in the future.

Closed by #2.
